# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Trang chủ"
  url = "#slider"
  weight = 10

[[main]]
  name = "Nổi bật"
  url = "#featured"
  weight = 20

[[main]]
  name = "Gần đây"
  url = "#posts"
  weight = 30

[[main]]
  name = "Giới thiệu"
  url = "#about"
  weight = 50

[[main]]
  name = "Thành viên"
  url = "#people"
  weight = 60

[[main]]
  name = "Liên hệ"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
