variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  image: monachus/hugo
  stage: build
  script:
    - hugo --cleanDestinationDir --gc
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  image: devillex/docker-firebase:slim
  stage: deploy
  only:
    - master
  script:
    - firebase deploy --token "$FIREBASE_TOKEN"
  # environment:
  #   name: production
  #   url: https://<project-name>.firebaseapp.com
  dependencies:
    - build
