backend:
  name: gitlab
  repo: duchoaofthings/duchoaofthings.web.app
  branch: master
  base_url: https://duchoaofthings.herokuapp.com

media_folder: "static/img/uploads/" # Folder where user uploaded files should go
public_folder: "/img/uploads/"

site_url: https://duchoaofthings.web.app/
display_url: https://duchoaofthings.web.app/
logo_url: https://duchoaofthings.web.app/img/logo.png
#locale: "vi"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "list" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          hint: "Main content goes here.",
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "LastMod", name: "lastmod", widget: "datetime" }
      - {
          label: "SubTitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Summary", name: "summary", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          required: false,
        }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - {
              label: "Caption",
              name: "caption",
              widget: "string",
              required: false,
            }
          - {
              label: "Focal Point",
              name: "focal_point",
              widget: "string",
              required: false,
            }
          - {
              label: "Preview Only",
              name: "preview_only",
              widget: "boolean",
              default: false,
              required: false,
            }
        required: false
      - { label: "Projects", name: "projects", widget: "list", required: false }
